  deploy:
      script:
        - apt-get update -qq && apt-get install -y -qq lftp
        - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnev ./ ./public_html/acme --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
        - apt-get install -y default-mysql-client
        - mysql --user="${DB_USER} --password="${$DB_PASSWORD}" --host="${$DB_HOST}" "${DB_DATABASE}"
        - mysql $DB_DATABASE < "./acme-db.sql"
      only:
        - master
