  deploy:
      before_script:
       - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
       - eval $(ssh-agent -s)
       - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
       - mkdir -p ~/.ssh
       - chmod 700 ~/.ssh
       - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      script:
        - ssh bitnami@104.197.171.107 "cd htdocs && git clone git@gitlab.com:idahogurl/acme2.git && git checkout master && git pull origin master && exit"
      only:
        - master