image: thywolf/alpine-openssh-client
deploy:
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 104.197.171.107 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - DIR="./htdocs/${USER}-acme"
    - echo $DIR
    - ssh bitnami@104.197.171.107 "rm -rf $DIR; mkdir $DIR"
    - scp -r ./* bitnami@104.197.171.107:$DIR
  only:
    - master
    - peer-review

